import { type Incident } from './types';

export const mockIncidents: Incident[] = [
  {
    id: '1',
    type: 'traffic',
    status: 'active',
    severity: 'high',
    location: { lat: 25, lng: 30 },
    title: 'Major Traffic Jam on Main St',
    description: 'A multi-car pile-up has blocked all lanes on Main Street near the city center. Emergency services are on the scene. Avoid the area if possible.',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: '2',
    type: 'infrastructure',
    status: 'active',
    severity: 'medium',
    location: { lat: 45, lng: 60 },
    title: 'Pothole Reported on Park Ave',
    description: 'A large and deep pothole has been reported on Park Avenue, causing issues for smaller vehicles. Awaiting city maintenance crew.',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '3',
    type: 'safety',
    status: 'active',
    severity: 'medium',
    location: { lat: 70, lng: 20 },
    title: 'Suspicious Activity near Library',
    description: 'Reports of a suspicious individual loitering near the public library after hours. Local police have been notified and are patrolling the area.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '4',
    type: 'infrastructure',
    status: 'resolved',
    severity: 'low',
    location: { lat: 80, lng: 80 },
    title: 'Streetlight Outage Resolved',
    description: 'The streetlight outage on 5th Avenue has been fixed by the utility company. All lights are now operational.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
    {
    id: '5',
    type: 'traffic',
    status: 'active',
    severity: 'low',
    location: { lat: 10, lng: 85 },
    title: 'Minor Congestion near Market',
    description: 'Slight traffic congestion due to market day rush. Delays are minimal but expected to continue for the next hour.',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: '6',
    type: 'safety',
    status: 'resolved',
    severity: 'high',
    location: { lat: 50, lng: 50 },
    title: 'Gas Leak Secured',
    description: 'The reported gas leak in the downtown area has been contained and secured by the fire department and gas company. The area is now safe.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
    {
    id: '7',
    type: 'infrastructure',
    status: 'active',
    severity: 'high',
    location: { lat: 90, lng: 40 },
    title: 'Water Main Break',
    description: 'A significant water main break on Elm Street is causing flooding and water pressure issues in the vicinity. Crews are en route.',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
];
